#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aqq index "${BASH_SOURCE##*/aqq-}" '
    import "aws" as aws;

    .AccountAliases
      | reduce flatten[] as $i ({}; .[$i] = {})
    ' "$@"
}

source sub "$BASH_SOURCE" "$@"
AccountAliases
imma
