#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aqq index "${BASH_SOURCE##*/aqq-}" '
    import "aws" as aws;

    .Images
      | aws::index(.ImageId)
      | aws::secondary(.Name)
    ' "$@"
}

source sub "$BASH_SOURCE" "$@"
