#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  (set +f; rm -f "$shome/.cache"/*.json)
  aqq all >/dev/null
}

source sub "$BASH_SOURCE" "$@"
