#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_resource="$1"; shift
  local jq_index="$1"; shift

  if [[ "$#" == 0 ]]; then
    set -- .
  fi

  if [[ ! -f "$shome/.cache/${nm_resource}.json" ]]; then
    mkdir -p "$shome/.cache"
    aq "$nm_resource" -L "$shome/jq" "$jq_index" > "$shome/.cache/${nm_resource}.json.$$"
    mv -f "$shome/.cache/${nm_resource}.json.$$" "$shome/.cache/${nm_resource}.json"
  fi

  cat "$shome/.cache/${nm_resource}.json" | jq -r -S "${@}"
}

source sub "$BASH_SOURCE" "$@"
