#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aqq index "${BASH_SOURCE##*/aqq-}" '
    import "aws" as aws;

    [.Reservations[].Instances] 
      | aws::index(.InstanceId) 
      | aws::secondary(.PrivateIpAddress)
      | aws::secondary(.PrivateDnsName)
      | aws::secondary(.PublicIpAddress)
      | aws::secondary(.PublicDnsName)
    ' "$@"
}

source sub "$BASH_SOURCE" "$@"
