#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- .
  fi

  aq instances -L "$shome/jq" 'import "aws" as aws; 
    [.Reservations[].Instances] 
      | aws::index(.InstanceId) 
      + aws::index(.PrivateIpAddress)
      + aws::index(.PrivateDnsName)
      + aws::index(.PublicIpAddress)
      + aws::index(.PublicDnsName)
    ' | jq -r -S "$@"
}

source sub "$BASH_SOURCE" "$@"
