#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aqq index "${BASH_SOURCE##*/aqq-}" '
    import "aws" as aws;

    .AutoScalingGroups
      | aws::index(.AutoScalingGroupARN) 
      + aws::index(.AutoScalingGroupName) 
    ' "$@"
}

source sub "$BASH_SOURCE" "$@"
AutoScalingGroups
{
  "AutoScalingGroupARN": "arn:aws:autoscaling:us-west-1:548373030883:autoScalingGroup:f4761c33-b3bf-4544-954b-e27fc723c706:autoScalingGroupName/imma-admin-cache-default-asg",
  "AutoScalingGroupName": "imma-admin-cache-default-asg",
  "AvailabilityZones": [
    "us-west-1b",
    "us-west-1c"
  ],
  "CreatedTime": "2016-06-29T08:25:34.081Z",
  "DefaultCooldown": 300,
  "DesiredCapacity": 0,
  "EnabledMetrics": [],
  "HealthCheckGracePeriod": 300,
  "HealthCheckType": "EC2",
  "Instances": [],
  "LaunchConfigurationName": "imma-admin-cache-default-lc-c5p3jrmx2nflrbwkbvsjrzdhua",
  "LoadBalancerNames": [
    "imma-admin-cache-default-elb"
  ],
  "MaxSize": 0,
  "MinSize": 0,
  "NewInstancesProtectedFromScaleIn": false,
  "SuspendedProcesses": [],
  "Tags": [
    {
      "Key": "Agency",
      "PropagateAtLaunch": true,
      "ResourceId": "imma-admin-cache-default-asg",
      "ResourceType": "auto-scaling-group",
      "Value": "asg"
    },
    {
      "Key": "App",
      "PropagateAtLaunch": true,
      "ResourceId": "imma-admin-cache-default-asg",
      "ResourceType": "auto-scaling-group",
      "Value": "cache"
    },
    {
      "Key": "Provisioner",
      "PropagateAtLaunch": true,
      "ResourceId": "imma-admin-cache-default-asg",
      "ResourceType": "auto-scaling-group",
      "Value": "tf"
    },
    {
      "Key": "Service",
      "PropagateAtLaunch": true,
      "ResourceId": "imma-admin-cache-default-asg",
      "ResourceType": "auto-scaling-group",
      "Value": "cache-default"
    }
  ],
  "TerminationPolicies": [
    "OldestInstance"
  ],
  "VPCZoneIdentifier": "subnet-ce3a1f97,subnet-6f28310a"
}
