#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aqq index "${BASH_SOURCE##*/aqq-}" '
    import "aws" as aws;

    .Roles
      | aws::index(.Arn) 
      | aws::secondary(.RoleId) 
      | aws::secondary(.RoleName) 
    ' "$@"
}

source sub "$BASH_SOURCE" "$@"
