#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aqq index "${BASH_SOURCE##*/aqq-}" '
    import "aws" as aws;

    .SecurityGroups
      | aws::index(.GroupId) 
      + aws::index(.GroupName) 
    ' "$@"
}

source sub "$BASH_SOURCE" "$@"
