#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aqq index "${BASH_SOURCE##*/aqq-}" '
    import "aws" as aws;

    .VirtualMFADevices
      | aws::index(.SerialNumber) 
      | aws::secondary(.User.Arn) 
      | aws::secondary(.User.UserId) 
      | aws::secondary(.User.UserName) 
    ' "$@"
}

source sub "$BASH_SOURCE" "$@"
