#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aqq index "${BASH_SOURCE##*/aqq-}" '
    import "aws" as aws;

    .Subscriptions
      | aws::index(.Endpoint) 
      + aws::index(.SubscriptionArn) 
    ' "$@"
}

source sub "$BASH_SOURCE" "$@"
