#!/usr/bin/env bash

function _aqq_profile {
  local shome="${_aqq_home:="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  PATH="$PATH:$shome/bin:$shome/exec"

  export AQQ_CACHE="${BOARD_PATH}/.aqq"
}

_aqq_profile
